huskyhustle/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from djangorestframework.resources import ModelResource
from djangorestframework.views import ListOrCreateModelView, InstanceModelView

from husky.views import BlogFeed
from husky.models import Parent, Children, Donation, Teacher, Grade

admin.autodiscover()


class TeacherResource(ModelResource):
    model = Teacher

class GradeResource(ModelResource):
    model = Grade

class ParentResource(ModelResource):
    model = Parent

class ChildrenResource(ModelResource):
    model = Children

class DonationResource(ModelResource):
    model = Donation

urlpatterns = patterns('',
    # Site
    url(r'^$', 'husky.views.index', name='index'),
    url(r'^archive/album/(?P<album_id>\w+)$', 'husky.views.album', name='albums'),
    url(r'^archive/photo/(?P<album_id>\w+)/(?P<photo_id>\w+)$', 'husky.views.photo', name='photo'),
    url(r'^nav/(?P<page>\w+)/*(?P<id>\d+)*$', 'husky.views.nav', name='nav'),
    url(r'^JSON/(?P<child_id>[\w-]+)$', 'husky.views.json', name='json'),
    url(r'^paid/(?P<donation_id>[\w,-]+)$', 'husky.views.paid', name='paid'),
    url(r'^thank_you/*(?P<donation_id>[\w-]+)*$', 'husky.views.thank_you', name='thank_you'),
    url(r'^link/(?P<parent_id>[\w-]+)$', 'husky.views.link', name='link'),
    url(r'^emails/*$', 'husky.views.emails', name='emails'),
    url(r'^reminders/*$', 'husky.views.reminders', name='reminders'),
    url(r'^thanks/*$', 'husky.views.thanks', name='thanks'),
    url(r'^donate/(?P<child_id>[\w-]+)$', 'husky.views.donate', name='donate'),
    url(r'^donate-direct$', 'husky.views.donate_direct', name='donate-direct'),
    url(r'^make-donation/(?P<identifier>[\w-]*)$', 'husky.views.make_donation', name='make-donation'),
    url(r'^payment/(?P<identifier>[\w-]+)/*(?P<id>[\d,]*)$', 'husky.views.payment', name='payment'),
    url(r'^teacher-donation/(?P<identifier>[\w-]*)$', 'husky.views.teacher_donation', name='teacher-donation'),
    url(r'^account/(?P<identifier>[\w-]+)*$', 'husky.views.account', name='account'),
    url(r'^donation_sheet/(?P<identifier>[\w-]+)*/(?P<final>[\w-]+)*$', 'husky.views.donation_sheet', name='donation_sheet'),
    url(r'^accounts/profile/$', 'husky.views.account', name='profile'),
    url(r'^add/(?P<type>[\w]+)*$', 'husky.views.add', name='add'),
    url(r'^edit/(?P<type>[\w]+)*$', 'husky.views.edit', name='edit'),
    url(r'^delete/(?P<type>[\w]+)*$', 'husky.views.delete', name='delete'),
    url(r'^contact/*$', 'husky.views.contact', name='contact'),
    url(r'^register/*$', 'husky.views.register', name='register'),
    url(r'^results/*(?P<type>[\w-]*)$', 'husky.views.results', name='results'),
    url(r'^activate/(?P<key>[\w]+)*$', 'husky.views.activate', name='activate'),
    url(r'^request/(?P<type>[\w]+)/(?P<key>[\w]+)*$', 'husky.views.request', name='request'),
    url(r'^disconnect/(?P<parent_id>[\w]+)/(?P<social>[\w]+)*$', 'husky.views.disconnect', name='disconnect'),

    # override password function
    url(r'^accounts/password/reset/$', 'husky.views.reset', name='password_reset'),
    url(r'^accounts/password/reset/done/$', 'husky.views.reset_done', name='password_reset_done'),
    url(r'^accounts/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'husky.views.reset_confirm', name='password_reset_confirm'),
    url(r'^accounts/password/reset/complete/$', 'husky.views.reset_complete', name='password_reset_complete'),

    # account registration
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^social/', include('socialregistration.urls', namespace = 'socialregistration')),

    # rss feed
    url(r'^blog/feed$', BlogFeed()),

    # reports
    url(r'^admin/reporting/(?P<type>[\w-]+)$', 'husky.views.reporting', name='reporting'),
    url(r'^admin/reports/(?P<type>[\w-]+)$', 'husky.views.reports', name='reports'),
    url(r'^admin/results/(?P<type>[\w-]*)/*(?P<grade>[\w]*)$', 'husky.views.results', name='results'),
    url(r'^admin/(?P<type>[\w]+)/calculate_totals/*(?P<id>[\d]*)$', 'husky.views.calculate_totals', name='calculate_totals'),
    url(r'^admin/send_teacher_reports/*(?P<id>[\d,]*)$', 'husky.views.send_teacher_reports', name='send_teacher_reports'),
    url(r'^admin/send_unpaid_reports$', 'husky.views.send_unpaid_reports', name='send_unpaid_reports'),
    url(r'^admin/send_unpaid_reminders/*(?P<type>[\w]*)/*(?P<donation_id>[\d]*)$', 'husky.views.send_unpaid_reminders', name='send_unpaid_reminders'),

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # REST API
    url(r'^REST/api-auth/', include('djangorestframework.urls', namespace='djangorestframework')),
    url(r'^REST/teacher/$', ListOrCreateModelView.as_view(resource=TeacherResource)),
    url(r'^REST/teacher/(?P<pk>[^/]+)/$', InstanceModelView.as_view(resource=TeacherResource)),
    url(r'^REST/grade/$', ListOrCreateModelView.as_view(resource=GradeResource)),
    url(r'^REST/grade/(?P<pk>[^/]+)/$', InstanceModelView.as_view(resource=GradeResource)),
    url(r'^REST/parent/$', ListOrCreateModelView.as_view(resource=ParentResource)),
    url(r'^REST/parent/(?P<pk>[^/]+)/$', InstanceModelView.as_view(resource=ParentResource)),
    url(r'^REST/children/$', ListOrCreateModelView.as_view(resource=ChildrenResource)),
    url(r'^REST/children/(?P<identifier>[^/]+)/$', InstanceModelView.as_view(resource=ChildrenResource)),
    url(r'^REST/donation/$', ListOrCreateModelView.as_view(resource=DonationResource)),
    url(r'^REST/donation/(?P<pk>[^/]+)/$', InstanceModelView.as_view(resource=DonationResource))
)

husky/models.py
import os
import csv
import pytz
import math
import base64
import urllib
import re as regexp
import datetime as date
import husky.bitly as bitly
import gdata.media as media
import gdata.photos.service as gdata
import gdata.calendar.client as cdata

from django.db import models
from django.db.models import Count, Sum, Avg, Max
from django.db.models.signals import post_save
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.sites.models import Site
from django import forms

from paypal import PayPal
from picasa import  PicasaField, PicasaStorage
from decimal import Decimal
from registration.forms import RegistrationForm

from socialregistration.contrib.facebook.models import FacebookProfile
from socialregistration.contrib.twitter.models import TwitterProfile
from socialregistration.contrib.openid.models import OpenIDProfile

from husky.helpers import *

DONATION_GOAL     = 50000
MAX_BAR_LENGTH    = 225
MAX_ARROW_HEIGHT  = 275
BASE_ARROW_HEIGHT = 73
RAFFLE_TICKET_AMT = 25


# Field Classes
class CurrencyField(models.DecimalField):

    def __init__(self, *args, **kwargs):
        kwargs['max_digits'] =  10
        kwargs['decimal_places'] = 2
        super(CurrencyField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        try:
            return super(CurrencyField, self).to_python(value).quantize(Decimal('0.01'))
        except AttributeError:
            return None


# Google Classes
class GoogleCalendarConnect(object):

    gd_client = cdata.CalendarClient(source=settings.PICASA_STORAGE_OPTIONS['source'])
    gd_client.ClientLogin(settings.PICASA_STORAGE_OPTIONS['email'], settings.PICASA_STORAGE_OPTIONS['password'], gd_client.source)

    def client(self):
        return self.gd_client


class GooglePhotoConnect(object):

    gd_client = gdata.PhotosService()
    gd_client.email = settings.PICASA_STORAGE_OPTIONS['email']
    gd_client.password = settings.PICASA_STORAGE_OPTIONS['password']
    gd_client.source = settings.PICASA_STORAGE_OPTIONS['source']
    gd_client.ProgrammaticLogin()

    def client(self):
        return self.gd_client


class Calendar(object):

    gd_client = GoogleCalendarConnect().client()

    def get_events(self):
        query = cdata.CalendarEventQuery()
        query.start_min = date.datetime.now().strftime('%Y-%m-%d')
#        query.start_max = (date.datetime.now() + date.timedelta(days=14)).strftime('%Y-%m-%d')
        feed = self.gd_client.GetCalendarEventFeed(q=query, visibility='public', sortorder='ascending', orderby='starttime')
        return feed


class Photo(object):

    gd_client = GooglePhotoConnect().client()

    def get_photo(self, album_id=None, photo_id=None):
        if not photo_id or not photo_id: return
        photo = self.gd_client.GetFeed('/data/feed/api/user/default/albumid/%s/photoid/%s' % (album_id, photo_id))
        return photo

    def get_photos(self, album_id=None):
        if not album_id: return
        photos = self.gd_client.GetFeed('/data/feed/api/user/default/albumid/%s?kind=photo' % (album_id))
        return photos

    def get_photos_by_tags(self, tags='huskyhustle'):
        photos = self.gd_client.GetFeed('/data/feed/api/all?kind=photo&tag=%s' % (tags))
        return photos


class Album(object):

    gd_client = GooglePhotoConnect().client()

    def get_album(self, album_id=None):
        if not album_id: return
        photos = Photo().get_photos(album_id)
        return photos

    def get_albums(self):
        albums = self.gd_client.GetUserFeed(user=settings.PICASA_STORAGE_OPTIONS['userid'])
        return albums


# Create your models here.
class Content(models.Model):

    page = models.CharField(max_length=100)
    content = models.TextField(max_length=65000, blank=True, null=True)
    date_added = models.DateTimeField(default=date.datetime.now())


class Blog(models.Model):

    title = models.CharField(max_length=100)
    author = models.ForeignKey(User)
    content = models.TextField(max_length=4000)
    date_added = models.DateTimeField(default=date.datetime.now())


class Message(models.Model):

    title = models.CharField(max_length=100)
    author = models.ForeignKey(User)
    content = models.TextField(max_length=4000)
    date_added = models.DateTimeField(default=date.datetime.now())


class Link(models.Model):

    title = models.CharField(max_length=50)
    url = models.CharField(max_length=255)
    shorten = models.CharField(max_length=255)
    status = models.IntegerField(blank=True, null=True, choices=((0,0), (1,1)))

    def __unicode__(self):
        return self.title

    def shortened(self):
        if not self.shorten:
            api = bitly.Api(login=settings.BITLY_LOGIN, apikey=settings.BITLY_APIKEY)
            self.shorten = api.shorten(self.url)
            self.save()
        return self.shorten


class Grade(models.Model):

    grade = models.IntegerField(blank=True, null=True)
    title = models.CharField(max_length=15)

    def __unicode__(self):
        return self.title

    def get_all(self):
        return Grade.objects.exclude(grade=-1).all()

    def most_donations_avg(self):
        avg = self.total_collected() / self.total_students()
        return round(avg, 2)

    def most_laps_avg(self):
        avg = float(self.total_laps()) / self.total_students()
        return round(avg, 2)

    def total_students(self):
        return Children.objects.filter(teacher__grade=self).count()

    def total_laps(self):
        results = Children.objects.filter(teacher__grade=self).exclude(disqualify=True).aggregate(num_laps=Sum('laps'))
        return results['num_laps'] or 0

    def total_donations(self):
        results = Donation.objects.filter(child__teacher__grade=self).aggregate(total_donations=Sum('donated'))
        return float(results['total_donations'] or 0)

    def total_collected(self):
        results = Children.objects.filter(teacher__grade=self).aggregate(total_collected=Sum('collected'))
        return float(results['total_collected'] or 0)

    def percent_completed(self):
        percentage = 0
        if self.total_collected() and self.total_donations():
            percentage = self.total_collected() / self.total_donations()
        return round(percentage, 3)


class Teacher(models.Model):

    title = models.CharField(max_length=5, choices=(('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Miss', 'Miss'), ('Mr.', 'Mr.')), default='Mrs.')
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50)
    email_address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=25, blank=True, null=True, default='(714) 734-1878')
    room_number = models.CharField(max_length=5)
    website = models.CharField(max_length=255, blank=True, null=True)
    shorten = models.CharField(max_length=255, blank=True, null=True)
    grade = models.ForeignKey(Grade, related_name='teachers')
    list_type = models.IntegerField(blank=True, null=True)
    class Meta:
        ordering = ['last_name', 'first_name']

    def __unicode__(self):
        return '%s (%s) %s' % (self.full_name(), self.room_number, self.grade)

    def full_name(self):
        return '%s %s %s' % (self.title, self.first_name, self.last_name)

    def find(self, last_name=None):
        try:
            return Teacher.objects.filter(last_name__icontains=last_name).all()
        except ObjectDoesNotExist, e:
            return

    def total_students(self, exclude=None):
        if exclude and exclude == 1:
            return Children.objects.filter(teacher=self, laps__gt=0).exclude(disqualify=True).count()
        elif exclude and exclude == 2:
            return Children.objects.filter(teacher=self, collected__gt=0).count()
        else:
            return Children.objects.filter(teacher=self).count()

    def total_participation(self):
        return Children.objects.filter(teacher=self, collected__gt=0).count()

    def get_all(self):
        return Teacher.objects.exclude(grade__grade=-1).all()

    def get_donate_list(self):
        return Teacher.objects.exclude(list_type=2).order_by('grade','room_number').all()

    def get_list(self):
        return Teacher.objects.exclude(list_type=3).order_by('grade','room_number').all()

    def get_donations(self):
        total = Donation.objects.filter(child__teacher=self).aggregate(donated=Sum('donated'))
        return float(total['donated'] or 0)

    def get_donations_list(self):
        donators = []
        sponsors = []
        children = Children.objects.filter(teacher=self).all()
        for child in children:
            donation = child.total_sum()
            donators.append({'name': child.list_name(), 'total': float(donation['total_sum'] or 0)})
        donations = Donation.objects.filter(first_name__contains=self.last_name)
        totals = { }
        for index, donation in enumerate(donations):
            full_name = donation.child.list_name()
            if totals.has_key(full_name):
                totals[full_name] += donation.donated or 0
            else:
                totals[full_name] = donation.donated or 0
        for child, total in iter(sorted(totals.iteritems())):
            sponsors.append({'name': child, 'total': float(total or 0)})
        return donators, sponsors

    def shortened(self):
        if not self.shorten:
            api = bitly.Api(login=settings.BITLY_LOGIN, apikey=settings.BITLY_APIKEY)
            self.shorten = api.shorten(self.website)
            self.save()
        return self.shorten

    def reports_url(self):
        site = Site.objects.get_current()
        reports_url = 'http://%s/admin/results/donations-by-teacher?id=%s' % (site.domain, self.id)
        return reports_url


class Children(models.Model):

    first_name = models.CharField(max_length=50)

husky/templates/include/child-form.html
{% if edit %}
{% for child in parent.children.all %}
<form action="/edit/child" method="post" id="child_{{ child.id }}" class="form-edit hidden">
	{% csrf_token %}
	<input type="hidden" value="{{ child.id }}" name="id" />
	<ol>
		<li><label for="first_name">First Name:</label><input id="first_name" type="text" name="first_name" value="{{ child.first_name }}" size="30" class="required" /><span class="hidden pad-left10 error">* required</span></li>
		<li><label for="last_name">Last Name:</label><input id="last_name" type="text" name="last_name" value="{{ child.last_name }}" size="30" class="required" /><span class="hidden pad-left10 error">* required</span></li>
		<li>
			<label for="teacher">Teacher:</label>
			<select name="teacher">
				{% for teacher in teachers %}
				<option value="{{ teacher.id }}"{% if child.teacher == teacher %}selected="selected"{% endif %}>{{ teacher }}</option>
				{% endfor %}
			</select>
		</li>
		<li>&nbsp;</li>
		<li>
			<input type="button" style="width: 9em;" class="control input submit_edit" id="submit_child_{{ child.id }}" value=" Update Student " />
		</li>
	</ol>
</form>
{% endfor %}
{% else %}
<form action="/add/child" method="post" id="form_child">
	{% csrf_token %}
	<ol>
		<li><label for="id_first_name"{% if form.first_name.errors %} class="error"{% endif %}>First Name:</label><input id="id_first_name" type="text" name="first_name" value="" size="30" class="required" />{% if form.first_name.errors %}<span class="pad-left10 error">* required</span>{% endif %}</li>
		<li><label for="id_last_name"{% if form.last_name.errors %} class="error"{% endif %}>Last Name:</label><input id="id_last_name" type="text" name="last_name" value="{{ form.last_name.value }}" size="30" class="required" />{% if form.last_name.errors %}<span class="pad-left10 error">* required</span>{% endif %}</li>
		<li>
			<label for="teacher">Teacher:</label>
			<select name="teacher">
				{% for teacher in teachers %}
				<option value="{{ teacher.id }}">{{ teacher }}</option>
				{% endfor %}
			</select>
		</li>
		<li><input type="button" style="width: 8em;" class="control input submit" id="submit_child" value=" Add Student " /></li>
	</ol>
</form>
{% endif %}

husky/templates/include/menu.html
<header class="clearfix" id="mobile">
	<div class="container">
		<div id="logo">
			<h1><a href="#">Husky Hustle</a></h1>
		</div>
		<nav class="clearfix">
			{% if request.user.is_authenticated %}
			<div style="float: right;padding-right: 10px;font-size: 0.75em;line-height: 1.5em;">Logged in as: {{ parent.full_name }}<br /><a href="/accounts/logout/">Logout</a></div>
			<br class="clearfix" />
			{% endif %}
			<ul role="navigation">
				<li class="first"><a href="/">Home</a></li>
				<!--li{% if 'results' in request.path %} class="current_page_item"{% endif %}><a href="/results">Results</a></li-->
				<li{% if 'photos' in request.path %} class="current_page_item"{% endif %}><a href="/nav/photos">Photos</a></li>
				<li{% if 'blog' in request.path %} class="current_page_item"{% endif %}><a href="/nav/blog">Blog</a></li>
				<li{% if 'links' in request.path %} class="current_page_item"{% endif %}><a href="/nav/links">Links</a></li>
				<li{% if 'contact' in request.path %} class="current_page_item"{% endif %}><a href="/nav/contact">Contact</a></li>
				{% if request.user.is_authenticated %}
				<li {% if 'account' in request.path %}class="current_page_item"{% endif %}><a href="/accounts/profile/">Profile</a></li>
				{% else %}
				<li class="last"><a href="/accounts/login">Login / Register</a></li>
				{% endif %}
			</ul>
		</nav>
	</div>
</header>
<div id="header">
	{% if request.user.is_authenticated %}
	<div style="float: right;font-size: 0.75em;line-height: 1.5em;">Logged in as: {{ parent.full_name }}<br /><a href="/accounts/logout/">Logout</a></div>
	{% endif %}
	<div id="logo">
		<h1><a href="#">Husky Hustle</a></h1>
	</div>
	<div id="menu">
		<ul>
			<li class="first"><a href="/">Home</a></li>
			<!--li{% if 'results' in request.path %} class="current_page_item"{% endif %}><a href="/results">Results</a></li-->
			<li{% if 'photos' in request.path %} class="current_page_item"{% endif %}><a href="/nav/photos">Photos</a></li>
			<li{% if 'blog' in request.path %} class="current_page_item"{% endif %}><a href="/nav/blog">Blog</a></li>
			<li{% if 'links' in request.path %} class="current_page_item"{% endif %}><a href="/nav/links">Links</a></li>
			<li{% if 'contact' in request.path %} class="current_page_item"{% endif %}><a href="/nav/contact">Contact</a></li>
			{% if request.user.is_authenticated %}
			<li {% if 'account' in request.path %}class="current_page_item"{% endif %}><a href="/accounts/profile/">Profile</a></li>
			{% else %}
			<li class="last"><a href="/accounts/login">Login / Register</a></li>
			{% endif %}
		</ul>
		<br class="clearfix" />
	</div>
</div>

husky/templates/include/page-footer.html
			&copy; 2012 useEvil, Inc. | Developed by <a href="http://www.thaiandhien.com/">Thai Nguyen</a> | <a href="/nav/privacy">Privacy Policy</a>

husky/templates/include/register-form.html
{% if edit %}
<form action="/edit/{% if as_parent %}parent{% else %}profile{% endif %}" method="post" id="{% if as_parent %}parent{% else %}profile{% endif %}_{{ parent.id }}" class="form-edit hidden">
	{% csrf_token %}
	<input type="hidden" value="{{ parent.id }}" name="id" />
	<ol>
		<li><label for="first_name">First Name:</label><input id="first_name" type="text" name="first_name" value="{{ parent.first_name }}" size="30" class="required" /><span class="hidden pad-left10 error">* required</span></li>
		<li><label for="last_name">Last Name:</label><input id="last_name" type="text" name="last_name" value="{{ parent.last_name }}" size="30" class="required" /><span class="hidden pad-left10 error">* required</span></li>
		<li><label for="email_address">Email Address:</label><input id="email_address" type="text" name="email_address" value="{{ parent.email_address }}" size="30" maxlength="75" class="required" /><span class="hidden pad-left10 error">* required</span></li>
		<li><label for="phone_number">Phone Number:</label><input id="phone_number" type="text" name="phone_number" value="{{ parent.phone_number }}" size="30" class="required" placeholder="(xxx) xxx-xxxx" /><span class="hidden pad-left10 error">* required</span></li>
		<li><label for="guardian">&nbsp;</label>
			<select id="guardian" name="guardian">
				<option value="1"{% if parent.guardian == 1 %} selected="selected"{% endif %}>Mother</option>
				<option value="2"{% if parent.guardian == 2 %} selected="selected"{% endif %}>Father</option>
				<option value="3"{% if parent.guardian == 3 %} selected="selected"{% endif %}>Guardian</option>
			</select>
		</li>
		<li>&nbsp;</li>
		<li>
			<input type="button" style="width: 8em;" class="control input submit_edit" id="submit_{% if as_parent %}parent{% else %}profile{% endif %}_{{ parent.id }}" value=" Update Profile " />
		</li>
	</ol>
</form>
{% else %}
<form action="/register/" method="post">
	{% csrf_token %}
	<ol>
		<li><label for="id_first_name"{% if form.first_name.errors %} class="error"{% endif %}>First Name:</label><input id="id_first_name" type="text" name="first_name" value="{{ form.first_name.value }}" size="30" class="required" /><span class="pad-left10 require error">*{% if form.first_name.errors %} required{% endif %}</span></li>
		<li><label for="id_last_name"{% if form.last_name.errors %} class="error"{% endif %}>Last Name:</label><input id="id_last_name" type="text" name="last_name" value="{{ form.last_name.value }}" size="30" class="required" /><span class="pad-left10 require error">*{% if form.last_name.errors %} required{% endif %}</span></li>
		<li><label for="id_email_address"{% if form.email_address.errors %} class="error"{% endif %}>Email Address:</label><input id="id_email_address" type="text" name="email_address" value="{{ form.email_address.value }}" size="30" maxlength="75" class="required" /><span class="pad-left10 require error">*{% if form.email_address.errors %} required{% endif %}</span></li>
		<li><label for="id_phone_number"{% if form.phone_number.errors %} class="error"{% endif %}>Phone Number:</label><input id="id_phone_number" type="text" name="phone_number" value="{{ form.phone_number.value }}" size="30" class="required" placeholder="(xxx) xxx-xxxx" /></li>
		<li><label for="id_guardian">&nbsp;</label>
			<select id="id_guardian" name="guardian">
				<option value="1"{% if form.guardian.value == 1 %} selected="selected"{% endif %}>Mother</option>
				<option value="2"{% if form.guardian.value == 2 %} selected="selected"{% endif %}>Father</option>
				<option value="3"{% if form.guardian.value == 3 %} selected="selected"{% endif %}>Guardian</option>
			</select>
		</li>
		{% if request.path == '/register/' %}
		<li><label for="id_password1"{% if form.non_field_errors or not form.password1.value %} class="error"{% endif %}>Password:</label><input id="id_password1" type="password" name="password1" value="" size="15" class="required" /><span class="pad-left10 require error">*{% if form.non_field_errors or not form.password1.value %} required{% endif %}</span></li>
		<li><label for="id_password2"{% if form.non_field_errors or not form.password2.value %} class="error"{% endif %}>Confirm:</label><input id="id_password2" type="password" name="password2" value="" size="15" class="required" /><span class="pad-left10 require error">*{% if form.non_field_errors or not form.password2.value %} required{% endif %}</span></li>
		{% else %}
		<li><label for="id_password1">Password:</label><input id="id_password1" type="password" name="password1" value="" size="15" class="required" /><span class="pad-left10 require error">*</span></li>
		<li><label for="id_password2">Confirm:</label><input id="id_password2" type="password" name="password2" value="" size="15" class="required" /><span class="pad-left10 require error">*</span></li>
		{% endif %}
		<li><input type="submit" value=" Register " /></li>
	</ol>
</form>
{% endif %}

husky/templates/include/social-form.html
<span>Please update your Profile Information</span>
<form action="/social/setup/" method="post">
	{% csrf_token %}
	<ol>
		<li><label for="id_first_name"{% if form.first_name.errors %} class="error"{% endif %}>First Name:</label><input id="id_first_name" type="text" name="first_name" value="{% if data %}{{ data.first_name }}{% else %}{{ form.initial.form.first_name }}{% endif %}" size="30" class="required" /><span class="pad-left10 error">* required</span></li>
		<li><label for="id_last_name"{% if form.last_name.errors %} class="error"{% endif %}>Last Name:</label><input id="id_last_name" type="text" name="last_name" value="{% if data %}{{ data.last_name }}{% else %}{{ form.initial.form.last_name }}{% endif %}" size="30" class="required" /><span class="pad-left10 error">* required</span></li>
		<li><label for="id_email"{% if error_email %} class="error"{% endif %}>Email Address:</label><input id="id_email" type="text" name="email" value="{% if data %}{{ data.email_address }}{% endif %}" size="30" class="required" /><span class="pad-left10 error">* required</span></li>
		<li><label for="id_phone_number"{% if form.phone_number.errors %} class="error"{% endif %}>Phone Number:</label><input id="id_phone_number" type="text" name="phone_number" value="{% if data %}{{ data.phone_number }}{% endif %}" size="30" placeholder="(xxx) xxx-xxxx" /></li>
		<li><label for="guardian">&nbsp;</label>
			<select id="guardian" name="guardian">
				<option value="1">Mother</option>
				<option value="2">Father</option>
				<option value="3">Guardian</option>
			</select>
		</li>
		<li><input type="submit" value=" Register " /></li>
	</ol>
</form>